import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { Bar } from "react-chartjs-2";
import Chart from 'chart.js/auto';
import Card from "react-bootstrap/Card";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>The Kenwood Commute</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          The Kenwood Commute
        </h1>

        <p className={styles.description}>
          An archival of commutes around Lake of the Isles, savored
        </p>

        <div style={{ maxWidth: "650px" }}>
        <Bar
          data={{
            // Name of the variables on x-axies for each bar
            labels: ["Ski", "Drive", "Walk", "Bike"],
            datasets: [
              {
                // Label for bars
                label: "Days",
                // Data or value of your each variable
                data: [8, 5, 3, 2],
                // Color of each bar
                backgroundColor: ["aqua", "green", "red", "yellow"],
                // Border color of each bar
                borderColor: ["aqua", "green", "red", "yellow"],
                borderWidth: 0.5,
              },
            ],
          }}
          // Height of graph
          height={400}
          options={{
            maintainAspectRatio: false,
            scales: {
              yAxes: [
                {
                  ticks: {
                    // The y-axis value will start from zero
                    beginAtZero: true,
                  },
                },
              ],
            },
            legend: {
              labels: {
                fontSize: 15,
              },
            },
          }}
        />
      </div>

      <div className={styles.post}>
      <h1>12/29/2021: The Route</h1>


      <Image src="https://i.imgur.com/5MeS7ZA.png" width="500px" height="300px" />

      <p>
          When walking, this is the most pleasant path from my house to the office. When the lake is frozen, the preffered way is across the ice width wise. When the lake is open, I can take a watercraft.
      </p>
      

    </div>

    <div className={styles.post}>
      <h1>12/29/2021: The Motivation</h1>

      <Image src="https://images.fineartamerica.com/images/artworkimages/mediumlarge/2/autumn-on-lake-of-the-isles-mark-ryan.jpg" width="500px" height="300px"/>

      <p>
          All too often, the friction points in our life detract from the contents that they surround, which are actually quite wonderful and pure. The average American commute is full of rush and detatchment from the moment. From my old commute, wherein I primarily drove, I remember more about my frantically checking the time than I do about the city views on I94. I decided to start this blog to take a radically differnt attitude towards commuting - one that cherishes the moment, appreciates natural beauty, and ultimately improves the experience I have in the rest of my work day. To that end, I thought that gathering blog post and photograph artificats of my commutes and share them publicly would not only be a fun thing to share with friends and family, but would drive me to achieve the goals that I have in a commute. In addition to the blog posts, you will see that I have started a log of commute types - that is in order to stay away from the mundane, you need to take radical approaches to things in life, and switching up the commute medium is going to be a good thing for this endeavor. Today on the chart, for example, you can see that I have predominatly skied on my new commute and it has been oh so sweet.
      </p>
      

    </div>




      </main>

      <footer className={styles.footer}>
        Hosted with Love from Kenwood
      </footer>
    </div>
  )
}
